services:

  backend:
    volumes:
      - ./app:/app
    environment:
      START: runserver
    healthcheck:
      disable: true

  backend_migrate:
    volumes:
      - ./app:/app


networks:
  google_indexer: {}