services:
  database:
    image: postgis/postgis:16-3.4
    environment:
      - "POSTGRES_PASSWORD=pgpassword"
      - "POSTGRES_DB=google_indexer_backend"
    networks:
      - google_indexer
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
  redis:
    image: redis:5
    networks:
      - google_indexer
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend: &backend
    build:
      context: .
    restart: always
    depends_on:
      - database
      - redis
    ports:
      - "8000:8000"
    networks:
    - google_indexer
    environment:
      START: gunicorn
      DJANGO_SETTINGS_MODULE: google_indexer.settings.prod


  backend_huey:
    <<: *backend
    restart: always
    deploy:
      replicas: 4

    environment:
      START: huey
      DJANGO_SETTINGS_MODULE: google_indexer.settings.prod
    ports: []
    healthcheck:
      disable: true
    depends_on:
      - database
      - redis

  backend_migrate:
    <<: *backend
    container_name: google_indexer_backend_migrate
    restart: on-failure

    environment:
      START: migrate
    ports: []
    healthcheck:
      disable: true
    depends_on:
      - database



networks:
  google_indexer: {}

volumes:
  postgres:
