services:

  backend:
    volumes:
      - ./app:/app
    environment:
      START: runserver
    healthcheck:
      disable: true
    restart: no

  backend_migrate:

    volumes:
      - ./app:/app


networks:
  google_indexer: {}