services:
  database:
    image: postgis/postgis:16-3.4
    environment:
      - "POSTGRES_PASSWORD=pgpassword"
      - "POSTGRES_DB=google_indexer_backend"
    networks:
      - google_indexer
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
  redis:
    image: redis:5
    networks:
      - google_indexer
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend: &backend
    build:
      context: .
    container_name: google_indexer_backend
    restart: always
    ports:
      - "8000:8000"
    networks:
    - google_indexer
    environment:
      START: gunicorn


  backend_huey:
    <<: *backend
    container_name: google_indexer_huey
    restart: always

    environment:
      START: huey
    ports: []
    healthcheck:
      disable: true

  backend_migrate:
    <<: *backend
    container_name: google_indexer_backend_migrate
    restart: on-failure

    environment:
      START: migrate
    ports: []
    healthcheck:
      disable: true



networks:
  google_indexer: {}

volumes:
  postgres: