services:

  backend:
    volumes:
      - ./app:/app
    environment:
      START: runserver
      DJANGO_SETTINGS_MODULE: google_indexer.settings.dev
    healthcheck:
      disable: true
    restart: no


  backend_migrate:

    volumes:
      - ./app:/app


networks:
  google_indexer: {}