# Generated by Django 5.1.1 on 2024-09-29 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('VALID', 'valid'), ('INVALID', 'invalid')], default='VALID', max_length=255)),
                ('content', models.JSONField()),
                ('last_usage', models.DateTimeField(blank=True, null=True)),
                ('count_of_the_day', models.IntegerField(default=0)),
                ('max_per_day', models.IntegerField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sitemap_url', models.URLField()),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('PENDING', 'pending'), ('OK', 'up to date')], default='CREATED', max_length=255)),
                ('next_update', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('0_CREATED', 'created'), ('1_PENDING_VERIFICATION', 'pending verification'), ('2_NEED_INDEXATION', 'need indexation'), ('3_PENDING_INDEXATION_CALL', 'pending indexation call'), ('4_PENDING_INDEXATION_WAIT', 'pending indexation by google'), ('5_INDEXED', 'indexed')], default='0_CREATED', max_length=255)),
                ('next_verification', models.DateTimeField(blank=True, null=True)),
                ('last_verification', models.DateTimeField(blank=True, null=True)),
                ('last_indexation', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='indexer.trackedsite')),
            ],
        ),
    ]
