# Generated by Django 5.1.1 on 2024-10-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0003_alter_apikey_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedsite',
            name='next_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
