# Generated by Django 5.1.1 on 2024-10-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0005_remove_trackedpage_last_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedsite',
            name='admin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid')], default='VALID', max_length=255),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='usage',
            field=models.CharField(choices=[('APIKEY_USAGE_INDEXATION', 'Indexing'), ('APIKEY_USAGE_VERIFICATION', 'Checking')], default='APIKEY_USAGE_INDEXATION', max_length=255),
        ),
        migrations.AlterField(
            model_name='trackedpage',
            name='status',
            field=models.CharField(choices=[('2_NEED_INDEXATION', 'Need indexation'), ('3_PENDING_INDEXATION_CALL', 'Pending indexation call'), ('5_INDEXED', 'Indexed')], default='2_NEED_INDEXATION', max_length=255),
        ),
        migrations.AlterField(
            model_name='trackedsite',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('HOLD', 'Hold'), ('OK', 'Up to date')], default='CREATED', max_length=255),
        ),
    ]
